version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ostock_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
    environment:
      - ENCRYPT_KEY=uE]zzP0NiN$$p
    networks:
      backend:
        aliases:
          - "configserver"
  licenseservice:
    image: ostock/license:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: "default,dev"
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
      DATABASE_SERVER_PORT: "5432"
      DATABASE_SERVER: "database"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge